version: '2'

services:
  apt-cacher-ng:
    build: .
    image: sameersbn/apt-cacher-ng:latest
    restart: unless-stopped
    ports:
    - "3142:3142"
    volumes:
    - /srv/docker/apt-cacher-ng:/var/cache/apt-cacher-ng
